attraction('borough_market').
attraction('british_museum').
attraction('buckingham_palace').
attraction('camden_market').
attraction('churchill_war_rooms_museum').
attraction('covent_garden').
attraction('design_museum').
attraction('greenwich_observatory_and_the_prime_meridian').
attraction('hampstead_heath').
attraction('hyde_park').
attraction('imperial_war_museum').
attraction('kew_gardens_royal_botanic_gardens').
attraction('london_eye').
attraction('london_zoo').
attraction('madame_tussauds_wax_museum').
attraction('natural_history_museum').
attraction('notting_hill_and_portobello_road_market').
attraction('palace_of_westminster_parliament').
attraction('royal_opera_house').
attraction('science_museum').
attraction('shakespeares_globe_theatre').
attraction('sherlock_holmes_museum').
attraction('st_pauls_cathedral').
attraction('tate_modern').
attraction('tower_bridge').
attraction('tower_of_london').
attraction('trafalgar_square').
attraction('victoria_and_albert_museum').
attraction('west_end_theatre_district_leicester_square').
attraction('zsl_london_aquarium').
prop('borough_market','latitude',51.504514).
prop('borough_market','longitude',-0.090198).
prop('borough_market','neighbourhood','southwark').
prop('british_museum','latitude',51.519406).
prop('british_museum','longitude',-0.127643).
prop('british_museum','neighbourhood','camden').
prop('buckingham_palace','latitude',51.501364).
prop('buckingham_palace','longitude',-0.141889).
prop('buckingham_palace','neighbourhood','westminster').
prop('camden_market','latitude',51.541341).
prop('camden_market','longitude',-0.1476).
prop('camden_market','neighbourhood','camden').
prop('churchill_war_rooms_museum','latitude',51.502101).
prop('churchill_war_rooms_museum','longitude',-0.129175).
prop('churchill_war_rooms_museum','neighbourhood','westminster').
prop('covent_garden','latitude',51.511731).
prop('covent_garden','longitude',-0.12327).
prop('covent_garden','neighbourhood','camden').
prop('design_museum','latitude',51.47274).
prop('design_museum','longitude',-0.185164).
prop('design_museum','neighbourhood','kensington_and_chelsea').
prop('greenwich_observatory_and_the_prime_meridian','latitude',51.477928).
prop('greenwich_observatory_and_the_prime_meridian','longitude',0.000716).
prop('greenwich_observatory_and_the_prime_meridian','neighbourhood','greenwich').
prop('hampstead_heath','latitude',51.560731).
prop('hampstead_heath','longitude',-0.165782).
prop('hampstead_heath','neighbourhood','camden').
prop('hyde_park','latitude',51.50735).
prop('hyde_park','longitude',-0.1651).
prop('hyde_park','neighbourhood','westminster').
prop('imperial_war_museum','latitude',51.495968).
prop('imperial_war_museum','longitude',-0.108423).
prop('imperial_war_museum','neighbourhood','lambeth').
prop('kew_gardens_royal_botanic_gardens','latitude',51.478744).
prop('kew_gardens_royal_botanic_gardens','longitude',-0.296866).
prop('kew_gardens_royal_botanic_gardens','neighbourhood','richmond_upon_thames').
prop('london_eye','latitude',51.503324).
prop('london_eye','longitude',-0.119543).
prop('london_eye','neighbourhood','lambeth').
prop('london_zoo','latitude',51.535178).
prop('london_zoo','longitude',-0.153527).
prop('london_zoo','neighbourhood','camden').
prop('madame_tussauds_wax_museum','latitude',51.5225).
prop('madame_tussauds_wax_museum','longitude',-0.156836).
prop('madame_tussauds_wax_museum','neighbourhood','westminster').
prop('natural_history_museum','latitude',51.496753).
prop('natural_history_museum','longitude',-0.176634).
prop('natural_history_museum','neighbourhood','kensington_and_chelsea').
prop('notting_hill_and_portobello_road_market','latitude',51.516262).
prop('notting_hill_and_portobello_road_market','longitude',-0.208031).
prop('notting_hill_and_portobello_road_market','neighbourhood','kensington_and_chelsea').
prop('palace_of_westminster_parliament','latitude',51.499633).
prop('palace_of_westminster_parliament','longitude',-0.124755).
prop('palace_of_westminster_parliament','neighbourhood','westminster').
prop('royal_opera_house','latitude',51.51347).
prop('royal_opera_house','longitude',-0.121998).
prop('royal_opera_house','neighbourhood','camden').
prop('science_museum','latitude',51.497992).
prop('science_museum','longitude',-0.174436).
prop('science_museum','neighbourhood','kensington_and_chelsea').
prop('shakespeares_globe_theatre','latitude',51.5076).
prop('shakespeares_globe_theatre','longitude',-0.097607).
prop('shakespeares_globe_theatre','neighbourhood','southwark').
prop('sherlock_holmes_museum','latitude',51.523685).
prop('sherlock_holmes_museum','longitude',-0.158964).
prop('sherlock_holmes_museum','neighbourhood','westminster').
prop('st_pauls_cathedral','latitude',51.513845).
prop('st_pauls_cathedral','longitude',-0.098351).
prop('st_pauls_cathedral','neighbourhood','city_of_london').
prop('tate_modern','latitude',51.507774).
prop('tate_modern','longitude',-0.099597).
prop('tate_modern','neighbourhood','southwark').
prop('tower_bridge','latitude',51.505456).
prop('tower_bridge','longitude',-0.075356).
prop('tower_bridge','neighbourhood','southwark').
prop('tower_of_london','latitude',51.508112).
prop('tower_of_london','longitude',-0.075949).
prop('tower_of_london','neighbourhood','city_of_london').
prop('trafalgar_square','latitude',51.507987).
prop('trafalgar_square','longitude',-0.128048).
prop('trafalgar_square','neighbourhood','westminster').
prop('victoria_and_albert_museum','latitude',51.496639).
prop('victoria_and_albert_museum','longitude',-0.17218).
prop('victoria_and_albert_museum','neighbourhood','kensington_and_chelsea').
prop('west_end_theatre_district_leicester_square','latitude',51.510707).
prop('west_end_theatre_district_leicester_square','longitude',-0.130762).
prop('west_end_theatre_district_leicester_square','neighbourhood','westminster').
prop('zsl_london_aquarium','latitude',51.5018).
prop('zsl_london_aquarium','longitude',-0.1195).
prop('zsl_london_aquarium','neighbourhood','lambeth').
